apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Values.mysql.appName }}
    namespace: {{ .Values.namespace }}
    labels:
       app: {{ .Values.mysql.labels.app }}
spec:
    selector:
       matchLabels:
            app: {{ .Values.mysql.labels.app }}
    template:
       metadata:
            labels:
               app: {{ .Values.mysql.labels.app }}
       spec:
            containers:
               - name: {{ .Values.mysql.labels.containername }}
                 image: {{ .Values.mysql.labels.containerimg }}
                 env:
                    - name: {{ .Values.mysql.labels.envname }}
                      value: {{ .Values.mysql.labels.envval }}
                 volumeMounts:
                    - name: {{ .Values.mysql.volume.name }}
                      mountPath: {{ .Values.mysql.volume.mountpath }}
            volumes:
              - name: {{ .Values.mysql.volume.name }}
                persistentVolumeClaim:
                      claimName: {{ .Values.mysql.volume.volclaimname }}

---

apiVersion: v1
kind: Service
metadata:
   name: {{ .Values.mysql.appName }}
   namespace: {{ .Values.namespace }}
   labels:
      app: {{ .Values.mysql.labels.app }}
spec:
   ports:
      - name: {{ .Values.mysql.type }}
        port: {{ .Values.mysql.sqlport }}
   selector:
        app: {{ .Values.mysql.labels.app }}
