apiVersion: apps/v1
kind: Deployment
metadata:
        name: myk8sdeployment
        namespace: ks-ns
        labels:
                app: myk8s_app
spec:
        template:
                metadata:
                        labels:
                                app: myk8s_app1
                spec:
                    containers:
                        - name: my-java-app
                          image: hassandocker1/my_java_image:v1                
        selector:
                matchLabels:
                        app: myk8s_app1


---
                        
apiVersion: v1
kind: Service
metadata:
        name: myk8service
        namespace: ks-ns
        labels:
                app: myk8s_svc
spec:
        selector:
                app: myk8s_app1
        ports:
                - name: http
                  port: 80   #Exposing to the user
                  targetPort: 8080  #From the container
        type: LoadBalancer          
